package com.tianjian.login.model;

/**
 * SecurityConfigMenus generated by MyEclipse Persistence Tools
 */

public class SecurityConfigMenus implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -8900806184202653910L;

	private String id;
	/** 模块 */
	private SecurityConfigPublic securityConfigPublicObject;
	/** 菜单 */
	private SecurityConfigMenus securityConfigMenusObject;
	/** 菜单ID */
	private String menuCode;
	/** 菜单内容 */
	private String menuDetail;
	/** 解释说明 */
	private String menuNotice;
	/** 链接地址 */
	private String menuUrl;
	/** 末节点标志 */
	private Long endLevelFlag;
	/** 级别 */
	private Long menuLevel;
	/** 级别内序号 */
	private Long menuSeq;
	/** 图标 */
	private String menuIcon;
	/** 节点挂数据 */
	private String menuData;
	/** 目标窗口 */
	private String menuTarget;
	/** 方法 */
	private String menuMethod;
	/** 备注 */
	private String comments;
	/** 模块ID */
	private String securityConfigPublicId;
	/** 父类菜单ID */
	private String parentId;
	/** 序号 */
	private Long serialNo;
	/** 输入码 */
	private String inputCode;
	// Constructors
	private Long displayType;
	/** 菜单 */
	private Long menuType;
	/** 终端类型 */
	private String isFlatMenu;
	/** 租户id */
	private String tenantId;

	/** default constructor */
	public SecurityConfigMenus() {
	}

	/** minimal constructor */
	public SecurityConfigMenus(SecurityConfigPublic securityConfigPublic,
			String menuCode) {
		this.securityConfigPublicObject = securityConfigPublic;
		this.menuCode = menuCode;
	}

	/** full constructor */
	public SecurityConfigMenus(String id,
			SecurityConfigPublic securityConfigPublic,
			SecurityConfigMenus securityConfigMenus, String menuCode,
			String menuDetail, String menuNotice, String menuUrl,
			Long endLevelFlag, Long menuLevel, Long menuSeq, String menuIcon,
			String menuData, String menuTarget, String menuMethod,
			String comments, Long serialNo, String inputCode, Long displayType,
			Long menuType) {
		this.id = id;
		this.securityConfigPublicObject = securityConfigPublic;
		this.securityConfigMenusObject = securityConfigMenus;
		this.menuCode = menuCode;
		this.menuDetail = menuDetail;
		this.menuNotice = menuNotice;
		this.menuUrl = menuUrl;
		this.endLevelFlag = endLevelFlag;
		this.menuLevel = menuLevel;
		this.menuSeq = menuSeq;
		this.menuIcon = menuIcon;
		this.menuData = menuData;
		this.menuTarget = menuTarget;
		this.menuMethod = menuMethod;
		this.comments = comments;
		this.serialNo = serialNo;
		this.inputCode = inputCode;
		this.displayType = displayType;
		this.menuType = menuType;
	}

	// Property accessors

	public Long getMenuType() {
		return menuType;
	}

	public void setMenuType(Long menuType) {
		this.menuType = menuType;
	}

	public Long getDisplayType() {
		return displayType;
	}

	public void setDisplayType(Long displayType) {
		this.displayType = displayType;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SecurityConfigPublic getSecurityConfigPublicObject() {
		return this.securityConfigPublicObject;
	}

	public void setSecurityConfigPublicObject(
			SecurityConfigPublic securityConfigPublic) {
		this.securityConfigPublicObject = securityConfigPublic;
	}

	public SecurityConfigMenus getSecurityConfigMenusObject() {
		return this.securityConfigMenusObject;
	}

	public void setSecurityConfigMenusObject(
			SecurityConfigMenus securityConfigMenus) {
		this.securityConfigMenusObject = securityConfigMenus;
	}

	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	public String getMenuDetail() {
		return this.menuDetail;
	}

	public void setMenuDetail(String menuDetail) {
		this.menuDetail = menuDetail;
	}

	public String getMenuNotice() {
		return this.menuNotice;
	}

	public void setMenuNotice(String menuNotice) {
		this.menuNotice = menuNotice;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public Long getEndLevelFlag() {
		return this.endLevelFlag;
	}

	public void setEndLevelFlag(Long endLevelFlag) {
		this.endLevelFlag = endLevelFlag;
	}

	public Long getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(Long menuLevel) {
		this.menuLevel = menuLevel;
	}

	public Long getMenuSeq() {
		return this.menuSeq;
	}

	public void setMenuSeq(Long menuSeq) {
		this.menuSeq = menuSeq;
	}

	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	public String getMenuData() {
		return this.menuData;
	}

	public void setMenuData(String menuData) {
		this.menuData = menuData;
	}

	public String getMenuTarget() {
		return this.menuTarget;
	}

	public void setMenuTarget(String menuTarget) {
		this.menuTarget = menuTarget;
	}

	public String getMenuMethod() {
		return this.menuMethod;
	}

	public void setMenuMethod(String menuMethod) {
		this.menuMethod = menuMethod;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSecurityConfigPublicId() {
		return securityConfigPublicId;
	}

	public void setSecurityConfigPublicId(String securityConfigPublicId) {
		this.securityConfigPublicId = securityConfigPublicId;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public Long getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(Long serialNo) {
		this.serialNo = serialNo;
	}

	public String getInputCode() {
		return inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getIsFlatMenu() {
		return isFlatMenu;
	}

	public void setIsFlatMenu(String isFlatMenu) {
		this.isFlatMenu = isFlatMenu;
	}

	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}
}