package com.tianjian.security.bean;

/**
 * SecurityRoleVsMenus generated by MyEclipse Persistence Tools
 */

public class SecurityRoleVsMenus {

	// Fields
	private String id;
	/**备注*/
	private String comments;
	/**角色ID*/
	private String securityConfigRolesId;
	/**菜单ID*/
	private String securityConfigMenusId;
	// Constructors

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSecurityConfigRolesId() {
		return securityConfigRolesId;
	}

	public void setSecurityConfigRolesId(String securityConfigRolesId) {
		this.securityConfigRolesId = securityConfigRolesId;
	}

	public String getSecurityConfigMenusId() {
		return securityConfigMenusId;
	}

	public void setSecurityConfigMenusId(String securityConfigMenusId) {
		this.securityConfigMenusId = securityConfigMenusId;
	}

}