package com.tianjian.hsp.bean;

import java.util.List;

/**
 * 医疗机构基本信息字典表单
 * CommDistrictDict generated by MyEclipse - Hibernate Tools
 * @author chenxl
 */
public class HspConfigBaseinfoForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4772775917920779461L;

    private String id = "";
	private String itemCode = "";
	private String itemName = "";
	private String parentItemCode = "";
	private String commConfigUnittypeId = "";
	private String commConfigUnitgradeId = "";
	private String commConfigEconkindId = "";
	private String commConfigLocationId1 = "";
	private String commConfigLocationId2 = "";
	private String commConfigLocationId3 = "";
	private String commConfigLocationTownId = "";
	private String commClvId = "";
	private String address = "";
	private String zipcode = "";
	private String phone = "";
	private String dateClinicNum = "";
	private String yearOuthospitalNum = "";
	private String authorizedBedNum = "";
	private String outspreadBedNum = "";
	private String doctorNum = "";
	private String nurseNum = "";
	private String technicPersonNum = "";
	private String sickroomNum = "";
	private String operationroomNum = "";
	private String comments = "";
	private String seqNo = "";
	private String inputCode = "";
	private String levelDesc = "";
	private String commConfigHospitalTypeId = "";
	private String commConfigHospitalTypeName = "";
	private String commConfigFtManageId = "";
	private String EMail = "";
	private String domainName = "";
	private String createDate = "";
	private String createUserId = "";
	private String createUserName = "";
	private String parentItemName = "";
	private String commConfigUnittypeName = "";
	private String commConfigUnitgradeName = "";
	private String cchtName = "";
	private String commConfigFtManageName = "";
	private String commConfigEconkindName = "";
	private String commConfigLocationName1 = "";
	private String commConfigLocationName2 = "";
	private String commConfigLocationName3 = "";
	private String ccltName = "";
	private String commClvName = "";
	private String contactPersonName = "";
	private String commConfigSetTypes="";
	private String commConfigCovaffrss="";
	private String staffId="";
	private String staff;
	private String staffHspId = "";

	private String isPhoto="";
	private String staffHsp;
	private String staffName;
	private String tseqno;
	//乡镇
	private String town = "";
	private String village = "";
	private String hspConfigBaseInfo="";
	//年份
	private int year;
	private String govaffrs="";
	//是否颁发证书
	private String isGetCer = ""; 
	private String hcaId = ""; 
	private String caCode = "";
	private String caName = "";
	private String passWord = "";
	private String hspConfigBaseInfoId1="";
	private String hspConfigBaseInfoId2="";
	private String hspConfigBaseInfoId3="";
	private String hspConfigBaseInfoId4="";
	private String hspConfigBaseInfoId5="";
	private String hspConfigBaseInfoId1Name="";
	private String hspConfigBaseInfoId2Name="";
	private String hspConfigBaseInfoId3Name="";
	private String hspConfigBaseInfoId4Name="";
	private String hspConfigBaseInfoId5Name="";
	private String parentItemCode_name="";

	private String verbId="";
	private String message="";
	private String idHidden; //供修改.删除使用
	private String orderNo="";
	private String asc="";
 //	-----------list查询-----------------------------------------------
	private String[] idList;
	private String[] itemCodeList;
	private String[] itemNameList;
	private String[] addressList;
	private String[] commConfigUnittypeIdList;
	private String[] commConfigUnittypeNameList;
	private String[] commConfigUnitgradeIdList;
	private String[] commConfigUnitgradeNameList;
	private String[] seqNoList;
	private String[] phoneList;
	private String[] contactPersonNameList;
	private String[] commConfigSetType;
	private String[] commConfigCovaffrs;
	private String[] commConfigSetTypeId;
	private String[] commConfigCovaffrsId;
	

//	---------------------所有字典库处理-----------------------------------------------------------------
	private String[] commConfigUnittypeIds;
	private String[] commConfigUnittypeId_names;    //医疗机构类别

	private String[] commConfigUnitgradeIds;
	private String[] commConfigUnitgradeId_names;   //医疗机构等级

	private String[] commConfigEconkindIds;
	private String[] commConfigEconkindId_names;     //经济性质	
	/**所属省*/
	private String[] commConfigLocationId1s;
	private String[] commConfigLocationId1_names;
	/**所属市*/
	private String[] commConfigLocationId2s;
	private String[] commConfigLocationId2_names;
	/**所属县*/
	private String[] commConfigLocationId3s;
	private String[] commConfigLocationId3_names;
	/**上级医疗机构*/
	private String[] parentItemCodes;
	private String[] parentItemCode_names;
	/**所属乡镇*/
	private String[] commConfigLocationTownIds;
	private String[] commConfigLocationTownId_names;
	/**村*/
	private String[] commClvIds;
	private String[] commClvId_names;

	private String[] commConfigFtManageIds;
	private String[] commConfigFtManageId_names;  //机构分类管理-更改

	private String[] commConfigHospitalTypeIds;
	private String[] commConfigHospitalTypeId_names;  //卫生机构类别	

	private List<?> c010501aList;	
	private List<?> c010501bList;
	
	/** 注销表*/
	private String logoutTime;
	private String logoutReason;
	private String createUserId1;
	private String createUserName1;
	private String hspConfigBaseinfoId;
	
	
	
	
	public String getIsPhoto() {
		return isPhoto;
	}
	public void setIsPhoto(String isPhoto) {
		this.isPhoto = isPhoto;
	}
	
	
	public String[] getAddressList() {
		return addressList;
	}
	public void setAddressList(String[] addressList) {
		this.addressList = addressList;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getItemCode() {
		return itemCode;
	}
	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}
	public String getItemName() {
		return itemName;
	}
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}
	
	public String getCommConfigLocationId1() {
		return commConfigLocationId1;
	}
	public void setCommConfigLocationId1(String commConfigLocationId1) {
		this.commConfigLocationId1 = commConfigLocationId1;
	}
	public String getCommConfigLocationId2() {
		return commConfigLocationId2;
	}
	public void setCommConfigLocationId2(String commConfigLocationId2) {
		this.commConfigLocationId2 = commConfigLocationId2;
	}
	public String getCommConfigLocationId3() {
		return commConfigLocationId3;
	}
	public void setCommConfigLocationId3(String commConfigLocationId3) {
		this.commConfigLocationId3 = commConfigLocationId3;
	}

	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getZipcode() {
		return zipcode;
	}
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	
	
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getSeqNo() {
		return seqNo;
	}
	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}
	public String getInputCode() {
		return inputCode;
	}
	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getCommConfigHospitalTypeId() {
		return commConfigHospitalTypeId;
	}
	public void setCommConfigHospitalTypeId(String commConfigHospitalTypeId) {
		this.commConfigHospitalTypeId = commConfigHospitalTypeId;
	}

	public String getEMail() {
		return EMail;
	}
	public void setEMail(String mail) {
		EMail = mail;
	}
	public String getDomainName() {
		return domainName;
	}
	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}
	public String getCreateDate() {
		return createDate;
	}
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}
	public String getCreateUserId() {
		return createUserId;
	}
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}
	public String getCreateUserName() {
		return createUserName;
	}
	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}
	
	public String getCchtName() {
		return cchtName;
	}
	public void setCchtName(String cchtName) {
		this.cchtName = cchtName;
	}
	
	public String getCommConfigLocationName1() {
		return commConfigLocationName1;
	}
	public void setCommConfigLocationName1(String commConfigLocationName1) {
		this.commConfigLocationName1 = commConfigLocationName1;
	}
	public String getCommConfigLocationName2() {
		return commConfigLocationName2;
	}
	public void setCommConfigLocationName2(String commConfigLocationName2) {
		this.commConfigLocationName2 = commConfigLocationName2;
	}
	public String getCommConfigLocationName3() {
		return commConfigLocationName3;
	}
	public void setCommConfigLocationName3(String commConfigLocationName3) {
		this.commConfigLocationName3 = commConfigLocationName3;
	}
	
	public String getContactPersonName() {
		return contactPersonName;
	}
	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}
	public String getIsGetCer() {
		return isGetCer;
	}
	public void setIsGetCer(String isGetCer) {
		this.isGetCer = isGetCer;
	}
	public String getHcaId() {
		return hcaId;
	}
	public void setHcaId(String hcaId) {
		this.hcaId = hcaId;
	}
	public String getCaCode() {
		return caCode;
	}
	public void setCaCode(String caCode) {
		this.caCode = caCode;
	}
	public String getCaName() {
		return caName;
	}
	public void setCaName(String caName) {
		this.caName = caName;
	}
	public String getPassWord() {
		return passWord;
	}
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}
	public String getVerbId() {
		return verbId;
	}
	public void setVerbId(String verbId) {
		this.verbId = verbId;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getIdHidden() {
		return idHidden;
	}
	public void setIdHidden(String idHidden) {
		this.idHidden = idHidden;
	}
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	public String getAsc() {
		return asc;
	}
	public void setAsc(String asc) {
		this.asc = asc;
	}
	public String[] getIdList() {
		return idList;
	}
	public void setIdList(String[] idList) {
		this.idList = idList;
	}
	public String[] getItemCodeList() {
		return itemCodeList;
	}
	public void setItemCodeList(String[] itemCodeList) {
		this.itemCodeList = itemCodeList;
	}
	public String[] getItemNameList() {
		return itemNameList;
	}
	public void setItemNameList(String[] itemNameList) {
		this.itemNameList = itemNameList;
	}
	public String[] getCommConfigUnittypeIdList() {
		return commConfigUnittypeIdList;
	}
	public void setCommConfigUnittypeIdList(String[] commConfigUnittypeIdList) {
		this.commConfigUnittypeIdList = commConfigUnittypeIdList;
	}
	public String[] getCommConfigUnittypeNameList() {
		return commConfigUnittypeNameList;
	}
	public void setCommConfigUnittypeNameList(String[] commConfigUnittypeNameList) {
		this.commConfigUnittypeNameList = commConfigUnittypeNameList;
	}
	public String[] getCommConfigUnitgradeIdList() {
		return commConfigUnitgradeIdList;
	}
	public void setCommConfigUnitgradeIdList(String[] commConfigUnitgradeIdList) {
		this.commConfigUnitgradeIdList = commConfigUnitgradeIdList;
	}
	public String[] getCommConfigUnitgradeNameList() {
		return commConfigUnitgradeNameList;
	}
	public void setCommConfigUnitgradeNameList(String[] commConfigUnitgradeNameList) {
		this.commConfigUnitgradeNameList = commConfigUnitgradeNameList;
	}
	public String[] getSeqNoList() {
		return seqNoList;
	}
	public void setSeqNoList(String[] seqNoList) {
		this.seqNoList = seqNoList;
	}
	public String[] getCommConfigLocationId1s() {
		return commConfigLocationId1s;
	}
	public void setCommConfigLocationId1s(String[] commConfigLocationId1s) {
		this.commConfigLocationId1s = commConfigLocationId1s;
	}
	public String[] getCommConfigLocationId1_names() {
		return commConfigLocationId1_names;
	}
	public void setCommConfigLocationId1_names(String[] commConfigLocationId1_names) {
		this.commConfigLocationId1_names = commConfigLocationId1_names;
	}
	public String[] getCommConfigLocationId2s() {
		return commConfigLocationId2s;
	}
	public void setCommConfigLocationId2s(String[] commConfigLocationId2s) {
		this.commConfigLocationId2s = commConfigLocationId2s;
	}
	public String[] getCommConfigLocationId2_names() {
		return commConfigLocationId2_names;
	}
	public void setCommConfigLocationId2_names(String[] commConfigLocationId2_names) {
		this.commConfigLocationId2_names = commConfigLocationId2_names;
	}
	public String[] getCommConfigLocationId3s() {
		return commConfigLocationId3s;
	}
	public void setCommConfigLocationId3s(String[] commConfigLocationId3s) {
		this.commConfigLocationId3s = commConfigLocationId3s;
	}
	public String[] getCommConfigLocationId3_names() {
		return commConfigLocationId3_names;
	}
	public void setCommConfigLocationId3_names(String[] commConfigLocationId3_names) {
		this.commConfigLocationId3_names = commConfigLocationId3_names;
	}
	
	
	public String[] getCommConfigHospitalTypeIds() {
		return commConfigHospitalTypeIds;
	}
	public void setCommConfigHospitalTypeIds(String[] commConfigHospitalTypeIds) {
		this.commConfigHospitalTypeIds = commConfigHospitalTypeIds;
	}
	public String[] getCommConfigHospitalTypeId_names() {
		return commConfigHospitalTypeId_names;
	}
	public void setCommConfigHospitalTypeId_names(
			String[] commConfigHospitalTypeId_names) {
		this.commConfigHospitalTypeId_names = commConfigHospitalTypeId_names;
	}
	public List<?> getC010501aList() {
		return c010501aList;
	}
	public void setC010501aList(List<?> list) {
		c010501aList = list;
	}
	public List<?> getC010501bList() {
		return c010501bList;
	}
	public void setC010501bList(List<?> list) {
		c010501bList = list;
	}
	
	public String[] getCommConfigSetType() {
		return commConfigSetType;
	}
	public void setCommConfigSetType(String[] commConfigSetType) {
		this.commConfigSetType = commConfigSetType;
	}
	public String[] getCommConfigCovaffrs() {
		return commConfigCovaffrs;
	}
	public void setCommConfigCovaffrs(String[] commConfigCovaffrs) {
		this.commConfigCovaffrs = commConfigCovaffrs;
	}
	public String[] getCommConfigSetTypeId() {
		return commConfigSetTypeId;
	}
	public void setCommConfigSetTypeId(String[] commConfigSetTypeId) {
		this.commConfigSetTypeId = commConfigSetTypeId;
	}
	public String[] getCommConfigCovaffrsId() {
		return commConfigCovaffrsId;
	}
	public void setCommConfigCovaffrsId(String[] commConfigCovaffrsId) {
		this.commConfigCovaffrsId = commConfigCovaffrsId;
	}
	
	public String getHspConfigBaseInfoId1() {
		return hspConfigBaseInfoId1;
	}
	public void setHspConfigBaseInfoId1(String hspConfigBaseInfoId1) {
		this.hspConfigBaseInfoId1 = hspConfigBaseInfoId1;
	}
	public String getHspConfigBaseInfoId2() {
		return hspConfigBaseInfoId2;
	}
	public void setHspConfigBaseInfoId2(String hspConfigBaseInfoId2) {
		this.hspConfigBaseInfoId2 = hspConfigBaseInfoId2;
	}
	public String getHspConfigBaseInfoId3() {
		return hspConfigBaseInfoId3;
	}
	public void setHspConfigBaseInfoId3(String hspConfigBaseInfoId3) {
		this.hspConfigBaseInfoId3 = hspConfigBaseInfoId3;
	}
	public String getHspConfigBaseInfoId4() {
		return hspConfigBaseInfoId4;
	}
	public void setHspConfigBaseInfoId4(String hspConfigBaseInfoId4) {
		this.hspConfigBaseInfoId4 = hspConfigBaseInfoId4;
	}
	public String getHspConfigBaseInfoId5() {
		return hspConfigBaseInfoId5;
	}
	public void setHspConfigBaseInfoId5(String hspConfigBaseInfoId5) {
		this.hspConfigBaseInfoId5 = hspConfigBaseInfoId5;
	}
	public String getParentItemCode_name() {
		return parentItemCode_name;
	}
	public void setParentItemCode_name(String parentItemCode_name) {
		this.parentItemCode_name = parentItemCode_name;
	}
	public String getHspConfigBaseInfoId1Name() {
		return hspConfigBaseInfoId1Name;
	}
	public void setHspConfigBaseInfoId1Name(String hspConfigBaseInfoId1Name) {
		this.hspConfigBaseInfoId1Name = hspConfigBaseInfoId1Name;
	}
	public String getHspConfigBaseInfoId2Name() {
		return hspConfigBaseInfoId2Name;
	}
	public void setHspConfigBaseInfoId2Name(String hspConfigBaseInfoId2Name) {
		this.hspConfigBaseInfoId2Name = hspConfigBaseInfoId2Name;
	}
	public String getHspConfigBaseInfoId3Name() {
		return hspConfigBaseInfoId3Name;
	}
	public void setHspConfigBaseInfoId3Name(String hspConfigBaseInfoId3Name) {
		this.hspConfigBaseInfoId3Name = hspConfigBaseInfoId3Name;
	}
	public String getHspConfigBaseInfoId4Name() {
		return hspConfigBaseInfoId4Name;
	}
	public void setHspConfigBaseInfoId4Name(String hspConfigBaseInfoId4Name) {
		this.hspConfigBaseInfoId4Name = hspConfigBaseInfoId4Name;
	}
	public String getHspConfigBaseInfoId5Name() {
		return hspConfigBaseInfoId5Name;
	}
	public void setHspConfigBaseInfoId5Name(String hspConfigBaseInfoId5Name) {
		this.hspConfigBaseInfoId5Name = hspConfigBaseInfoId5Name;
	}
	public String[] getPhoneList() {
		return phoneList;
	}
	public void setPhoneList(String[] phoneList) {
		this.phoneList = phoneList;
	}
	public String[] getContactPersonNameList() {
		return contactPersonNameList;
	}
	public void setContactPersonNameList(String[] contactPersonNameList) {
		this.contactPersonNameList = contactPersonNameList;
	}
	public String getStaffId() {
		return staffId;
	}
	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}
	public String getParentItemCode() {
		return parentItemCode;
	}
	public void setParentItemCode(String parentItemCode) {
		this.parentItemCode = parentItemCode;
	}
	public String getCommConfigUnittypeId() {
		return commConfigUnittypeId;
	}
	public void setCommConfigUnittypeId(String commConfigUnittypeId) {
		this.commConfigUnittypeId = commConfigUnittypeId;
	}
	public String getCommConfigUnitgradeId() {
		return commConfigUnitgradeId;
	}
	public void setCommConfigUnitgradeId(String commConfigUnitgradeId) {
		this.commConfigUnitgradeId = commConfigUnitgradeId;
	}
	public String getCommConfigEconkindId() {
		return commConfigEconkindId;
	}
	public void setCommConfigEconkindId(String commConfigEconkindId) {
		this.commConfigEconkindId = commConfigEconkindId;
	}
	public String getCommConfigLocationTownId() {
		return commConfigLocationTownId;
	}
	public void setCommConfigLocationTownId(String commConfigLocationTownId) {
		this.commConfigLocationTownId = commConfigLocationTownId;
	}
	public String getCommClvId() {
		return commClvId;
	}
	public void setCommClvId(String commClvId) {
		this.commClvId = commClvId;
	}
	public String getDateClinicNum() {
		return dateClinicNum;
	}
	public void setDateClinicNum(String dateClinicNum) {
		this.dateClinicNum = dateClinicNum;
	}
	public String getYearOuthospitalNum() {
		return yearOuthospitalNum;
	}
	public void setYearOuthospitalNum(String yearOuthospitalNum) {
		this.yearOuthospitalNum = yearOuthospitalNum;
	}
	public String getAuthorizedBedNum() {
		return authorizedBedNum;
	}
	public void setAuthorizedBedNum(String authorizedBedNum) {
		this.authorizedBedNum = authorizedBedNum;
	}
	public String getOutspreadBedNum() {
		return outspreadBedNum;
	}
	public void setOutspreadBedNum(String outspreadBedNum) {
		this.outspreadBedNum = outspreadBedNum;
	}
	public String getDoctorNum() {
		return doctorNum;
	}
	public void setDoctorNum(String doctorNum) {
		this.doctorNum = doctorNum;
	}
	public String getNurseNum() {
		return nurseNum;
	}
	public void setNurseNum(String nurseNum) {
		this.nurseNum = nurseNum;
	}
	public String getTechnicPersonNum() {
		return technicPersonNum;
	}
	public void setTechnicPersonNum(String technicPersonNum) {
		this.technicPersonNum = technicPersonNum;
	}
	public String getSickroomNum() {
		return sickroomNum;
	}
	public void setSickroomNum(String sickroomNum) {
		this.sickroomNum = sickroomNum;
	}
	public String getOperationroomNum() {
		return operationroomNum;
	}
	public void setOperationroomNum(String operationroomNum) {
		this.operationroomNum = operationroomNum;
	}
	public String getLevelDesc() {
		return levelDesc;
	}
	public void setLevelDesc(String levelDesc) {
		this.levelDesc = levelDesc;
	}
	public String getCommConfigFtManageId() {
		return commConfigFtManageId;
	}
	public void setCommConfigFtManageId(String commConfigFtManageId) {
		this.commConfigFtManageId = commConfigFtManageId;
	}
	public String getParentItemName() {
		return parentItemName;
	}
	public void setParentItemName(String parentItemName) {
		this.parentItemName = parentItemName;
	}
	public String getCommConfigUnittypeName() {
		return commConfigUnittypeName;
	}
	public void setCommConfigUnittypeName(String commConfigUnittypeName) {
		this.commConfigUnittypeName = commConfigUnittypeName;
	}
	public String getCommConfigUnitgradeName() {
		return commConfigUnitgradeName;
	}
	public void setCommConfigUnitgradeName(String commConfigUnitgradeName) {
		this.commConfigUnitgradeName = commConfigUnitgradeName;
	}
	public String getCommConfigFtManageName() {
		return commConfigFtManageName;
	}
	public void setCommConfigFtManageName(String commConfigFtManageName) {
		this.commConfigFtManageName = commConfigFtManageName;
	}
	public String getCommConfigEconkindName() {
		return commConfigEconkindName;
	}
	public void setCommConfigEconkindName(String commConfigEconkindName) {
		this.commConfigEconkindName = commConfigEconkindName;
	}
	public String getCcltName() {
		return ccltName;
	}
	public void setCcltName(String ccltName) {
		this.ccltName = ccltName;
	}
	public String getCommClvName() {
		return commClvName;
	}
	public void setCommClvName(String commClvName) {
		this.commClvName = commClvName;
	}
	public String getCommConfigSetTypes() {
		return commConfigSetTypes;
	}
	public void setCommConfigSetTypes(String commConfigSetTypes) {
		this.commConfigSetTypes = commConfigSetTypes;
	}
	public String getCommConfigCovaffrss() {
		return commConfigCovaffrss;
	}
	public void setCommConfigCovaffrss(String commConfigCovaffrss) {
		this.commConfigCovaffrss = commConfigCovaffrss;
	}
	public String[] getCommConfigUnittypeIds() {
		return commConfigUnittypeIds;
	}
	public void setCommConfigUnittypeIds(String[] commConfigUnittypeIds) {
		this.commConfigUnittypeIds = commConfigUnittypeIds;
	}
	public String[] getCommConfigUnittypeId_names() {
		return commConfigUnittypeId_names;
	}
	public void setCommConfigUnittypeId_names(String[] commConfigUnittypeId_names) {
		this.commConfigUnittypeId_names = commConfigUnittypeId_names;
	}
	public String[] getCommConfigUnitgradeIds() {
		return commConfigUnitgradeIds;
	}
	public void setCommConfigUnitgradeIds(String[] commConfigUnitgradeIds) {
		this.commConfigUnitgradeIds = commConfigUnitgradeIds;
	}
	public String[] getCommConfigUnitgradeId_names() {
		return commConfigUnitgradeId_names;
	}
	public void setCommConfigUnitgradeId_names(String[] commConfigUnitgradeId_names) {
		this.commConfigUnitgradeId_names = commConfigUnitgradeId_names;
	}
	public String[] getCommConfigEconkindIds() {
		return commConfigEconkindIds;
	}
	public void setCommConfigEconkindIds(String[] commConfigEconkindIds) {
		this.commConfigEconkindIds = commConfigEconkindIds;
	}
	public String[] getCommConfigEconkindId_names() {
		return commConfigEconkindId_names;
	}
	public void setCommConfigEconkindId_names(String[] commConfigEconkindId_names) {
		this.commConfigEconkindId_names = commConfigEconkindId_names;
	}
	public String[] getParentItemCodes() {
		return parentItemCodes;
	}
	public void setParentItemCodes(String[] parentItemCodes) {
		this.parentItemCodes = parentItemCodes;
	}
	public String[] getParentItemCode_names() {
		return parentItemCode_names;
	}
	public void setParentItemCode_names(String[] parentItemCode_names) {
		this.parentItemCode_names = parentItemCode_names;
	}
	public String[] getCommConfigLocationTownIds() {
		return commConfigLocationTownIds;
	}
	public void setCommConfigLocationTownIds(String[] commConfigLocationTownIds) {
		this.commConfigLocationTownIds = commConfigLocationTownIds;
	}
	public String[] getCommConfigLocationTownId_names() {
		return commConfigLocationTownId_names;
	}
	public void setCommConfigLocationTownId_names(
			String[] commConfigLocationTownId_names) {
		this.commConfigLocationTownId_names = commConfigLocationTownId_names;
	}
	public String[] getCommClvIds() {
		return commClvIds;
	}
	public void setCommClvIds(String[] commClvIds) {
		this.commClvIds = commClvIds;
	}
	public String[] getCommClvId_names() {
		return commClvId_names;
	}
	public void setCommClvId_names(String[] commClvId_names) {
		this.commClvId_names = commClvId_names;
	}
	public String[] getCommConfigFtManageIds() {
		return commConfigFtManageIds;
	}
	public void setCommConfigFtManageIds(String[] commConfigFtManageIds) {
		this.commConfigFtManageIds = commConfigFtManageIds;
	}
	public String[] getCommConfigFtManageId_names() {
		return commConfigFtManageId_names;
	}
	public void setCommConfigFtManageId_names(String[] commConfigFtManageId_names) {
		this.commConfigFtManageId_names = commConfigFtManageId_names;
	}
	public String getStaffHspId() {
		return staffHspId;
	}
	public void setStaffHspId(String staffHspId) {
		this.staffHspId = staffHspId;
	}
	public String getLogoutTime() {
		return logoutTime;
	}
	public void setLogoutTime(String logoutTime) {
		this.logoutTime = logoutTime;
	}
	public String getLogoutReason() {
		return logoutReason;
	}
	public void setLogoutReason(String logoutReason) {
		this.logoutReason = logoutReason;
	}
	public String getCreateUserId1() {
		return createUserId1;
	}
	public void setCreateUserId1(String createUserId1) {
		this.createUserId1 = createUserId1;
	}
	public String getCreateUserName1() {
		return createUserName1;
	}
	public void setCreateUserName1(String createUserName1) {
		this.createUserName1 = createUserName1;
	}
	public String getHspConfigBaseinfoId() {
		return hspConfigBaseinfoId;
	}
	public void setHspConfigBaseinfoId(String hspConfigBaseinfoId) {
		this.hspConfigBaseinfoId = hspConfigBaseinfoId;
	}
	public int getYear() {
		return year;
	}
	public void setYear(int year) {
		this.year = year;
	}
	public String getTown() {
		return town;
	}
	public void setTown(String town) {
		this.town = town;
	}
	public String getVillage() {
		return village;
	}
	public void setVillage(String village) {
		this.village = village;
	}
	public String getGovaffrs() {
		return govaffrs;
	}
	public void setGovaffrs(String govaffrs) {
		this.govaffrs = govaffrs;
	}
	public String getHspConfigBaseInfo() {
		return hspConfigBaseInfo;
	}
	public void setHspConfigBaseInfo(String hspConfigBaseInfo) {
		this.hspConfigBaseInfo = hspConfigBaseInfo;
	}
	public String getStaffHsp() {
		return staffHsp;
	}
	public void setStaffHsp(String staffHsp) {
		this.staffHsp = staffHsp;
	}
	public String getStaffName() {
		return staffName;
	}
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}
	public String getStaff() {
		return staff;
	}
	public void setStaff(String staff) {
		this.staff = staff;
	}
	public String getTseqno() {
		return tseqno;
	}
	public void setTseqno(String tseqno) {
		this.tseqno = tseqno;
	}
	public String getCommConfigHospitalTypeName() {
		return commConfigHospitalTypeName;
	}
	public void setCommConfigHospitalTypeName(String commConfigHospitalTypeName) {
		this.commConfigHospitalTypeName = commConfigHospitalTypeName;
	}
	
}
